services:
  - type: web
    name: sheryl-system-app
    runtime: python
    region: singapore
    branch: main
    autoDeploy: true
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn store_erp.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
