services:
  - type: web
    name: sheryl-system-app
    runtime: python
    region: singapore
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn store_erp.wsgi:application"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
