services:
  - type: web
    name: sheryl-system
    runtime: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn store_erp.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sheryl-system-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9

databases:
  - name: sheryl-system-db
    plan: free
    databaseName: sarisari_erp
    user: sheryl_user
    ipAllowList: []
