# Generated by Django 5.0.6 on 2026-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditlog_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottle_deposit_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deposit Charge Fee per Bottle'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_bottle_deposit',
            field=models.BooleanField(default=False, verbose_name='Requires Glass Bottle Deposit/Return'),
        ),
    ]
